### your site title here

title: Ibrahim Al Anshor
tagline: Website Developer
description: Halo! Saya adalah seorang web developer dengan pengalaman dalam membangun berbagai jenis website menggunakan Laravel dan Vue.js.

baseurl: "" #name of GitHub repository
url: "https://ibrahimalanshor.github.io" #custom url to be used instead of GitHub repository
email: #

# Social media links in footer
linkedin: "ibrahimalanshor"
github: "ibrahimalanshor"
instagram: "ibrahimalanshor"
twitter: "ibrahiminx"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-sitemap

webmaster_verifications:
  google: uQGWsE1AvnXlD-gvyTzOv7sMh7vZH7pSuZctArIi3Ws